### ISSUE TITLE
Add way to tell front and rearpack apart, once they are on the ground

### ISSUE THREAD

**Issue by Reacher107** [gruppe-adler/grad_apobs#8]
Currently it is very difficult to tell which part of the APOBS System is already on the Ground.

This could be done by adding the either "front" or "rear" to the ace interactions.
For example instead of "Open APOBS" the phrase "Open Front APOBS" could be added. (Same for Place Action)

This would make it a lot easier to tell what part is placed where.

**Comment by AdlerSalbei** [comment]
In the future you can tell the diffrence between both packs, by the writing on the top of the packs. 

I'll think about the other suggestions.
